/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ShippingAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6916149840100178089L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShippingAddress\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"card_id\",\"type\":\"string\"},{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"post_code\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShippingAddress> ENCODER =
      new BinaryMessageEncoder<ShippingAddress>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShippingAddress> DECODER =
      new BinaryMessageDecoder<ShippingAddress>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ShippingAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ShippingAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ShippingAddress>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ShippingAddress to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ShippingAddress from a ByteBuffer. */
  public static ShippingAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence card_id;
  @Deprecated public java.lang.CharSequence street;
  @Deprecated public java.lang.CharSequence state;
  @Deprecated public java.lang.CharSequence post_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShippingAddress() {}

  /**
   * All-args constructor.
   * @param card_id The new value for card_id
   * @param street The new value for street
   * @param state The new value for state
   * @param post_code The new value for post_code
   */
  public ShippingAddress(java.lang.CharSequence card_id, java.lang.CharSequence street, java.lang.CharSequence state, java.lang.CharSequence post_code) {
    this.card_id = card_id;
    this.street = street;
    this.state = state;
    this.post_code = post_code;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return card_id;
    case 1: return street;
    case 2: return state;
    case 3: return post_code;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: card_id = (java.lang.CharSequence)value$; break;
    case 1: street = (java.lang.CharSequence)value$; break;
    case 2: state = (java.lang.CharSequence)value$; break;
    case 3: post_code = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'card_id' field.
   * @return The value of the 'card_id' field.
   */
  public java.lang.CharSequence getCardId() {
    return card_id;
  }

  /**
   * Sets the value of the 'card_id' field.
   * @param value the value to set.
   */
  public void setCardId(java.lang.CharSequence value) {
    this.card_id = value;
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }

  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'post_code' field.
   * @return The value of the 'post_code' field.
   */
  public java.lang.CharSequence getPostCode() {
    return post_code;
  }

  /**
   * Sets the value of the 'post_code' field.
   * @param value the value to set.
   */
  public void setPostCode(java.lang.CharSequence value) {
    this.post_code = value;
  }

  /**
   * Creates a new ShippingAddress RecordBuilder.
   * @return A new ShippingAddress RecordBuilder
   */
  public static example.avro.ShippingAddress.Builder newBuilder() {
    return new example.avro.ShippingAddress.Builder();
  }

  /**
   * Creates a new ShippingAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShippingAddress RecordBuilder
   */
  public static example.avro.ShippingAddress.Builder newBuilder(example.avro.ShippingAddress.Builder other) {
    return new example.avro.ShippingAddress.Builder(other);
  }

  /**
   * Creates a new ShippingAddress RecordBuilder by copying an existing ShippingAddress instance.
   * @param other The existing instance to copy.
   * @return A new ShippingAddress RecordBuilder
   */
  public static example.avro.ShippingAddress.Builder newBuilder(example.avro.ShippingAddress other) {
    return new example.avro.ShippingAddress.Builder(other);
  }

  /**
   * RecordBuilder for ShippingAddress instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShippingAddress>
    implements org.apache.avro.data.RecordBuilder<ShippingAddress> {

    private java.lang.CharSequence card_id;
    private java.lang.CharSequence street;
    private java.lang.CharSequence state;
    private java.lang.CharSequence post_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.ShippingAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.card_id)) {
        this.card_id = data().deepCopy(fields()[0].schema(), other.card_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.street)) {
        this.street = data().deepCopy(fields()[1].schema(), other.street);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.post_code)) {
        this.post_code = data().deepCopy(fields()[3].schema(), other.post_code);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ShippingAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.ShippingAddress other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.card_id)) {
        this.card_id = data().deepCopy(fields()[0].schema(), other.card_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.street)) {
        this.street = data().deepCopy(fields()[1].schema(), other.street);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.post_code)) {
        this.post_code = data().deepCopy(fields()[3].schema(), other.post_code);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'card_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCardId() {
      return card_id;
    }

    /**
      * Sets the value of the 'card_id' field.
      * @param value The value of 'card_id'.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder setCardId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.card_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'card_id' field has been set.
      * @return True if the 'card_id' field has been set, false otherwise.
      */
    public boolean hasCardId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'card_id' field.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder clearCardId() {
      card_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }

    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.street = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder clearStreet() {
      street = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }

    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder setState(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'post_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostCode() {
      return post_code;
    }

    /**
      * Sets the value of the 'post_code' field.
      * @param value The value of 'post_code'.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder setPostCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.post_code = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'post_code' field has been set.
      * @return True if the 'post_code' field has been set, false otherwise.
      */
    public boolean hasPostCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'post_code' field.
      * @return This builder.
      */
    public example.avro.ShippingAddress.Builder clearPostCode() {
      post_code = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShippingAddress build() {
      try {
        ShippingAddress record = new ShippingAddress();
        record.card_id = fieldSetFlags()[0] ? this.card_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.street = fieldSetFlags()[1] ? this.street : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.post_code = fieldSetFlags()[3] ? this.post_code : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShippingAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShippingAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShippingAddress>
    READER$ = (org.apache.avro.io.DatumReader<ShippingAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
