/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ShoppingCartStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4128983173977257144L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShoppingCartStatus\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"cart_id\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShoppingCartStatus> ENCODER =
      new BinaryMessageEncoder<ShoppingCartStatus>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShoppingCartStatus> DECODER =
      new BinaryMessageDecoder<ShoppingCartStatus>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ShoppingCartStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ShoppingCartStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ShoppingCartStatus>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ShoppingCartStatus to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ShoppingCartStatus from a ByteBuffer. */
  public static ShoppingCartStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence cart_id;
  @Deprecated public java.lang.CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShoppingCartStatus() {}

  /**
   * All-args constructor.
   * @param cart_id The new value for cart_id
   * @param status The new value for status
   */
  public ShoppingCartStatus(java.lang.CharSequence cart_id, java.lang.CharSequence status) {
    this.cart_id = cart_id;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cart_id;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cart_id = (java.lang.CharSequence)value$; break;
    case 1: status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'cart_id' field.
   * @return The value of the 'cart_id' field.
   */
  public java.lang.CharSequence getCartId() {
    return cart_id;
  }

  /**
   * Sets the value of the 'cart_id' field.
   * @param value the value to set.
   */
  public void setCartId(java.lang.CharSequence value) {
    this.cart_id = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new ShoppingCartStatus RecordBuilder.
   * @return A new ShoppingCartStatus RecordBuilder
   */
  public static example.avro.ShoppingCartStatus.Builder newBuilder() {
    return new example.avro.ShoppingCartStatus.Builder();
  }

  /**
   * Creates a new ShoppingCartStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShoppingCartStatus RecordBuilder
   */
  public static example.avro.ShoppingCartStatus.Builder newBuilder(example.avro.ShoppingCartStatus.Builder other) {
    return new example.avro.ShoppingCartStatus.Builder(other);
  }

  /**
   * Creates a new ShoppingCartStatus RecordBuilder by copying an existing ShoppingCartStatus instance.
   * @param other The existing instance to copy.
   * @return A new ShoppingCartStatus RecordBuilder
   */
  public static example.avro.ShoppingCartStatus.Builder newBuilder(example.avro.ShoppingCartStatus other) {
    return new example.avro.ShoppingCartStatus.Builder(other);
  }

  /**
   * RecordBuilder for ShoppingCartStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShoppingCartStatus>
    implements org.apache.avro.data.RecordBuilder<ShoppingCartStatus> {

    private java.lang.CharSequence cart_id;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.ShoppingCartStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cart_id)) {
        this.cart_id = data().deepCopy(fields()[0].schema(), other.cart_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ShoppingCartStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.ShoppingCartStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.cart_id)) {
        this.cart_id = data().deepCopy(fields()[0].schema(), other.cart_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'cart_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCartId() {
      return cart_id;
    }

    /**
      * Sets the value of the 'cart_id' field.
      * @param value The value of 'cart_id'.
      * @return This builder.
      */
    public example.avro.ShoppingCartStatus.Builder setCartId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.cart_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cart_id' field has been set.
      * @return True if the 'cart_id' field has been set, false otherwise.
      */
    public boolean hasCartId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cart_id' field.
      * @return This builder.
      */
    public example.avro.ShoppingCartStatus.Builder clearCartId() {
      cart_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public example.avro.ShoppingCartStatus.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public example.avro.ShoppingCartStatus.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShoppingCartStatus build() {
      try {
        ShoppingCartStatus record = new ShoppingCartStatus();
        record.cart_id = fieldSetFlags()[0] ? this.cart_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShoppingCartStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShoppingCartStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShoppingCartStatus>
    READER$ = (org.apache.avro.io.DatumReader<ShoppingCartStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
