/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CartPayment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6530914847057633926L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CartPayment\",\"namespace\":\"example.avro\",\"fields\":[{\"name\":\"card_id\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CartPayment> ENCODER =
      new BinaryMessageEncoder<CartPayment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CartPayment> DECODER =
      new BinaryMessageDecoder<CartPayment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CartPayment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CartPayment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CartPayment>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CartPayment to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CartPayment from a ByteBuffer. */
  public static CartPayment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence card_id;
  @Deprecated public java.lang.CharSequence amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CartPayment() {}

  /**
   * All-args constructor.
   * @param card_id The new value for card_id
   * @param amount The new value for amount
   */
  public CartPayment(java.lang.CharSequence card_id, java.lang.CharSequence amount) {
    this.card_id = card_id;
    this.amount = amount;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return card_id;
    case 1: return amount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: card_id = (java.lang.CharSequence)value$; break;
    case 1: amount = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'card_id' field.
   * @return The value of the 'card_id' field.
   */
  public java.lang.CharSequence getCardId() {
    return card_id;
  }

  /**
   * Sets the value of the 'card_id' field.
   * @param value the value to set.
   */
  public void setCardId(java.lang.CharSequence value) {
    this.card_id = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.lang.CharSequence getAmount() {
    return amount;
  }

  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.CharSequence value) {
    this.amount = value;
  }

  /**
   * Creates a new CartPayment RecordBuilder.
   * @return A new CartPayment RecordBuilder
   */
  public static example.avro.CartPayment.Builder newBuilder() {
    return new example.avro.CartPayment.Builder();
  }

  /**
   * Creates a new CartPayment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CartPayment RecordBuilder
   */
  public static example.avro.CartPayment.Builder newBuilder(example.avro.CartPayment.Builder other) {
    return new example.avro.CartPayment.Builder(other);
  }

  /**
   * Creates a new CartPayment RecordBuilder by copying an existing CartPayment instance.
   * @param other The existing instance to copy.
   * @return A new CartPayment RecordBuilder
   */
  public static example.avro.CartPayment.Builder newBuilder(example.avro.CartPayment other) {
    return new example.avro.CartPayment.Builder(other);
  }

  /**
   * RecordBuilder for CartPayment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CartPayment>
    implements org.apache.avro.data.RecordBuilder<CartPayment> {

    private java.lang.CharSequence card_id;
    private java.lang.CharSequence amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.avro.CartPayment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.card_id)) {
        this.card_id = data().deepCopy(fields()[0].schema(), other.card_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CartPayment instance
     * @param other The existing instance to copy.
     */
    private Builder(example.avro.CartPayment other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.card_id)) {
        this.card_id = data().deepCopy(fields()[0].schema(), other.card_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'card_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCardId() {
      return card_id;
    }

    /**
      * Sets the value of the 'card_id' field.
      * @param value The value of 'card_id'.
      * @return This builder.
      */
    public example.avro.CartPayment.Builder setCardId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.card_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'card_id' field has been set.
      * @return True if the 'card_id' field has been set, false otherwise.
      */
    public boolean hasCardId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'card_id' field.
      * @return This builder.
      */
    public example.avro.CartPayment.Builder clearCardId() {
      card_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.lang.CharSequence getAmount() {
      return amount;
    }

    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public example.avro.CartPayment.Builder setAmount(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public example.avro.CartPayment.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CartPayment build() {
      try {
        CartPayment record = new CartPayment();
        record.card_id = fieldSetFlags()[0] ? this.card_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.amount = fieldSetFlags()[1] ? this.amount : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CartPayment>
    WRITER$ = (org.apache.avro.io.DatumWriter<CartPayment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CartPayment>
    READER$ = (org.apache.avro.io.DatumReader<CartPayment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
